server:
  port: 8082
  
spring:
  application:
    name: hystrix-feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
feign:
  hystrix:
    enabled: true

    
    