server:
  port: 8084
  
spring:
  application:
    name: hystrix-consumer

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true