server:
  port: 8082
  
spring:
  application:
    name: simple-consumer

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
    
logging:
  level:
    com.example.demo.client.UserFeignClient: debug

feign:
  hystrix:
    enabled: true
    