spring:
  application:
    name: cloud-config-client
  cloud:
    config:
      uri: http://localhost:8762
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true